// <auto-generated />
using System;
using Eazy.Credit.Security.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eazy.Credit.Security.Persistence.Data.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    [Migration("20240619154543_TransHeaderStage")]
    partial class TransHeaderStage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eazy.Credit.Security.Dtos.CreditScheduleSummaryDto", b =>
                {
                    b.Property<string>("AccountDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreditID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CummPrincipal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CummRepayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutstandPrincipal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrinPlusInt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrincipal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("datetime2");

                    b.ToTable("CreditScheduleSummary");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Dtos.GenerateRepaymentScheduleDto", b =>
                {
                    b.Property<short>("Base")
                        .HasColumnType("smallint");

                    b.Property<string>("CreditID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InterestRepayFreq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InterestRepayNextDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InterestRepayNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrincipalRepayFreq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrincipalRepayNextDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrincipalRepayNumber")
                        .HasColumnType("int");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Simulation")
                        .HasColumnType("bit");

                    b.Property<bool>("StaggeredRepayment")
                        .HasColumnType("bit");

                    b.Property<string>("TransID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UseExistingAnnuityAmount")
                        .HasColumnType("bit");

                    b.ToTable("GenerateRepaymentScheduleDto");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.ActionTakenStatus", b =>
                {
                    b.Property<string>("ActionCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActionMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActionCode");

                    b.ToTable("ActionTakenStatus", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.AssignRoleToLimit", b =>
                {
                    b.Property<string>("LimitId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserRoleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LimitId", "UserRoleID");

                    b.ToTable("AssignRoleToLimit", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.AssignRoleToWorkflowLevel", b =>
                {
                    b.Property<string>("LevelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkflowID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LevelID", "WorkflowID", "RoleID");

                    b.ToTable("AssignRoleToWorkflowLevel", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CBNBankCode", b =>
                {
                    b.Property<string>("CBNCode")
                        .HasMaxLength(0)
                        .HasColumnType("nvarchar(0)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NIPBankCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SortCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CBNCode");

                    b.ToTable("CBNBankCode", (string)null);
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.ChargeBaseCodes", b =>
                {
                    b.Property<string>("ChargeBaseCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CeilingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ChargeAppDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeAppFreq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeAppMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeBaseCodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeBaseDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeContraGLAcct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeDebitTrans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeRateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeTaxGLAcct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FloorAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentChargeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Tier")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("TimeAdded")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeLastModified")
                        .HasColumnType("time");

                    b.Property<string>("TransCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransCodeTax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChargeBaseCode");

                    b.ToTable("ChargeBaseCodes", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditCharge", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sequence"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeBaseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FreqCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastExecDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NextExecDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PostingDateAdded")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeAdded")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeLastModified")
                        .HasColumnType("time");

                    b.Property<string>("TransID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Upfront")
                        .HasColumnType("bit");

                    b.HasKey("Sequence");

                    b.HasIndex("CreditId");

                    b.ToTable("CreditChargesMaint", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditGuarantor", b =>
                {
                    b.Property<long>("SeqNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeqNo"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BusinessRegNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessTaxNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BvnNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertIncorp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChequeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorFullNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalConstitution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Liability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MainBusiness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pep")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PostingDateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("TelNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeAdded")
                        .HasColumnType("time");

                    b.Property<string>("TransID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeqNo");

                    b.HasIndex("CreditId");

                    b.ToTable("CreditGuarantorsMaint", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditMaintHist", b =>
                {
                    b.Property<string>("CreditId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddedApprovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AmountGranted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ArrearsRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("AutoRepayArrears")
                        .HasColumnType("bit");

                    b.Property<short>("BaseYear")
                        .HasColumnType("smallint");

                    b.Property<string>("BranchAdded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchApproved")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CapitalizeInterest")
                        .HasColumnType("bit");

                    b.Property<decimal>("CarryingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ConsentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCardNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateAddedApproved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateApproved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisbursementAccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EditMode")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EffectiveRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EquityContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExtAccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExtEntry")
                        .HasColumnType("bit");

                    b.Property<decimal>("FirstDisbursementAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FirstDisbursementDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FixedRepaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FixedRepaymentArrearsTreatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FixedRepaymentFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FixedRepaymentLastDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FixedRepaymentNextDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FixedRepaymentStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FundSourceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuaranteeCoverageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastDisbursementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalActionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MisofficeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ObserveLimit")
                        .HasColumnType("bit");

                    b.Property<string>("OnLendingCreditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnLendingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperativeAccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Overdraft")
                        .HasColumnType("bit");

                    b.Property<string>("OwnershipId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PostingDateApproved")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferredRepaymentAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredRepaymentBankCBNCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProdCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurposeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RepaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityCoverageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Tenor")
                        .HasColumnType("smallint");

                    b.Property<string>("TenorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeAdded")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TimeAddedApproved")
                        .HasColumnType("time");

                    b.Property<string>("TransID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UpfrontInterest")
                        .HasColumnType("bit");

                    b.Property<string>("WorkstationAdded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkstationApproved")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkstationIpadded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkstationIpapproved")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CreditId");

                    b.ToTable("CreditMaintHist", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditSchedulesHeader", b =>
                {
                    b.Property<string>("CreditId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AmortizeMoratoriumInterest")
                        .HasColumnType("bit");

                    b.Property<short>("BaseYear")
                        .HasColumnType("smallint");

                    b.Property<string>("ChargesArrearsTreatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InterestArrearsTreatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("InterestMorat")
                        .HasColumnType("smallint");

                    b.Property<string>("InterestMoratFreq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestRepayFreq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InterestRepayNextDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InterestRepayNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MoratoriumIntAppDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("MoratoriumIntApplied")
                        .HasColumnType("bit");

                    b.Property<decimal>("MoratoriumInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ObserveLimit")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PostingDateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrincipalArrearsTreatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("PrincipalMorat")
                        .HasColumnType("smallint");

                    b.Property<string>("PrincipalMoratFreq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrincipalRepayFreq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrincipalRepayNextDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrincipalRepayNumber")
                        .HasColumnType("int");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeAdded")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeLastModified")
                        .HasColumnType("time");

                    b.Property<string>("TransID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CreditId");

                    b.ToTable("CreditSchedulesHeadersMaint", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditSchedulesLine", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sequence"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ChargeBaseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Sequence");

                    b.HasIndex("TransId");

                    b.ToTable("CreditSchedulesLinesMaint", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditSchedulesLineHist", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sequence"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ChargeBaseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Sequence");

                    b.ToTable("CreditSchedulesLinesHist", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditSchedulesLinesIntTemp", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sequence"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("InterestDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Sequence");

                    b.ToTable("CreditSchedulesLinesIntTemp", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditSchedulesLinesIntTempSim", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sequence"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("InterestDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Sequence");

                    b.ToTable("CreditSchedulesLinesIntTempSim", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditSchedulesLinesSim", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sequence"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ChargeBaseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Sequence");

                    b.ToTable("CreditSchedulesLinesSim", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditSecurity", b =>
                {
                    b.Property<long>("SeqNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeqNo"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ForcedSaleValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PostingDateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityLocationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityRefNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityTitleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SecurityValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("TimeAdded")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeLastModified")
                        .HasColumnType("time");

                    b.Property<string>("TransID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValuerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeqNo");

                    b.HasIndex("CreditId");

                    b.ToTable("CreditCollateral", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditTran", b =>
                {
                    b.Property<string>("TransId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddedApprovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BranchAdded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchApproved")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cancellation")
                        .HasColumnType("bit");

                    b.Property<string>("ContraAccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraNarrative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateAddedApproved")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EditMode")
                        .HasColumnType("bit");

                    b.Property<decimal>("ExchRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MainNarrative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PostingDateApproved")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Reversed")
                        .HasColumnType("bit");

                    b.Property<bool>("ServiceIntFirst")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("TimeAdded")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TimeAddedApproved")
                        .HasColumnType("time");

                    b.Property<string>("TransCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkstationAdded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkstationApproved")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkstationIpadded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkstationIpapproved")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransId");

                    b.ToTable("CreditTrans", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.OrgBankCode", b =>
                {
                    b.Property<string>("BankCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BankCode");

                    b.ToTable("OrgBankCodes", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.OrgBankInfo", b =>
                {
                    b.Property<short>("Record")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Record"));

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Record");

                    b.ToTable("OrgBankInfo", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.OrgBranch", b =>
                {
                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AllowFcyTrans")
                        .HasColumnType("bit");

                    b.Property<string>("AxDataAreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchMnemonic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsuCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeadOpsCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeAdded")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeLastModified")
                        .HasColumnType("time");

                    b.HasKey("BranchCode");

                    b.ToTable("OrgBranches", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.PrmCountry", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryCode");

                    b.ToTable("PrmCountries", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.PrmNumberSequence", b =>
                {
                    b.Property<int>("NumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumberId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lockup")
                        .HasColumnType("bit");

                    b.Property<int>("NextNumber")
                        .HasColumnType("int");

                    b.Property<byte>("NumberLength")
                        .HasColumnType("tinyint");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Separator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumberId");

                    b.ToTable("PrmNumberSequence", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.PrmRoleLimit", b =>
                {
                    b.Property<string>("LimitId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("CummulativeLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LimitDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LowerLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UpperLimit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LimitId");

                    b.ToTable("PrmRoleLimit", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.PrmRulesBoolean", b =>
                {
                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParameterDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Value")
                        .HasColumnType("bit");

                    b.HasKey("Parameter");

                    b.ToTable("PrmRulesBoolean", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.PrmRulesNumber", b =>
                {
                    b.Property<short>("Parameter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Parameter"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Parameter");

                    b.ToTable("PrmRulesNumbers", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.PrmRulesText", b =>
                {
                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Parameter");

                    b.ToTable("PrmRulesText", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.PrmType", b =>
                {
                    b.Property<short>("TypeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("TypeCode"));

                    b.Property<string>("LabelCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UserDefined")
                        .HasColumnType("bit");

                    b.HasKey("TypeCode");

                    b.ToTable("PrmTypes", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.PrmTypesDetail", b =>
                {
                    b.Property<short>("TypeCode")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeCode", "Code");

                    b.ToTable("PrmTypesDetails", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.ProdMaster", b =>
                {
                    b.Property<string>("ProdCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ArrearsProdCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("('ZZZ')");

                    b.Property<byte>("CotchargeAppDay")
                        .HasColumnType("tinyint")
                        .HasColumnName("COTChargeAppDay");

                    b.Property<string>("CotchargeAppFreq")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("COTChargeAppFreq")
                        .HasDefaultValueSql("('M')")
                        .IsFixedLength();

                    b.Property<byte>("CotchargeAppMonth")
                        .HasColumnType("tinyint")
                        .HasColumnName("COTChargeAppMonth");

                    b.Property<string>("CotchargeBaseCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("COTChargeBaseCode")
                        .HasDefaultValueSql("('000')");

                    b.Property<string>("CreditClassSchemeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("('ZZZ')");

                    b.Property<byte>("CreditIntAppDay")
                        .HasColumnType("tinyint");

                    b.Property<string>("CreditIntAppFreq")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('M')")
                        .IsFixedLength();

                    b.Property<string>("CreditIntAppMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("((1))");

                    b.Property<byte>("CreditIntAppMonth")
                        .HasColumnType("tinyint");

                    b.Property<string>("CreditIntBaseCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("('000')");

                    b.Property<string>("CreditIntCalcBalType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("CurrCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("('0')");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DateLastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte>("DebitIntAppDay")
                        .HasColumnType("tinyint");

                    b.Property<string>("DebitIntAppFreq")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('M')")
                        .IsFixedLength();

                    b.Property<string>("DebitIntAppMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("((1))");

                    b.Property<byte>("DebitIntAppMonth")
                        .HasColumnType("tinyint");

                    b.Property<string>("DebitIntBaseCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("('000')");

                    b.Property<string>("DebitIntCalcBalType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("LastCotappDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("LastCOTAppDate")
                        .HasDefaultValueSql("('01/01/2010')");

                    b.Property<DateTime>("LastCreditIntAppDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("('01/01/2010')");

                    b.Property<DateTime>("LastDebitIntAppDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("('01/01/2010')");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PriorityOrder")
                        .HasColumnType("int");

                    b.Property<string>("ProdCatCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProdName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SegmentId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SegmentID")
                        .HasDefaultValueSql("('ZZZ')");

                    b.Property<string>("TierCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("('ZZZ')");

                    b.Property<TimeSpan>("TimeAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<TimeSpan>("TimeLastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ProdCode")
                        .HasName("PK_ProdMaster_1");

                    b.ToTable("ProdMaster", (string)null);
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.TransHeaderStage", b =>
                {
                    b.Property<string>("TransID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Workflow")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Workflowlevel")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransID", "Workflow", "Workflowlevel");

                    b.ToTable("TransHeaderStages", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.TransHeaderStatus", b =>
                {
                    b.Property<string>("StatusCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatusMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusCode");

                    b.ToTable("TransHeaderStatus", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.WorkflowLevel", b =>
                {
                    b.Property<string>("LevelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkflowID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AllowDocUpload")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FinalLevel")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LevelOrder")
                        .HasColumnType("int");

                    b.Property<string>("WorkflowLevelTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LevelID", "WorkflowID");

                    b.ToTable("WorkflowLevel", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.Workflows", b =>
                {
                    b.Property<string>("WorkflowID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkflowNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkflowTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkflowID");

                    b.ToTable("Workflows", "dbo");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditCharge", b =>
                {
                    b.HasOne("Eazy.Credit.Security.Entities.CreditMaintHist", "CreditMaintHist")
                        .WithMany("CreditCharge")
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditMaintHist");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditGuarantor", b =>
                {
                    b.HasOne("Eazy.Credit.Security.Entities.CreditMaintHist", "CreditMaintHist")
                        .WithMany("CreditGuarantors")
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditMaintHist");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditSchedulesLine", b =>
                {
                    b.HasOne("Eazy.Credit.Security.Entities.CreditSchedulesHeader", "Trans")
                        .WithMany()
                        .HasForeignKey("TransId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trans");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditSecurity", b =>
                {
                    b.HasOne("Eazy.Credit.Security.Entities.CreditMaintHist", "CreditMaintHist")
                        .WithMany("CreditSecurity")
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditMaintHist");
                });

            modelBuilder.Entity("Eazy.Credit.Security.Entities.CreditMaintHist", b =>
                {
                    b.Navigation("CreditCharge");

                    b.Navigation("CreditGuarantors");

                    b.Navigation("CreditSecurity");
                });
#pragma warning restore 612, 618
        }
    }
}
